"""todo text migrations

Revision ID: 3ca3ea2f3d13
Revises: f9f974ad9b23
Create Date: 2022-09-03 03:08:21.860093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca3ea2f3d13'
down_revision = 'f9f974ad9b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'note')
    # ### end Alembic commands ###
