"""todo text migrations

Revision ID: ed047684ee24
Revises: 3ca3ea2f3d13
Create Date: 2022-09-03 14:02:27.190107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed047684ee24'
down_revision = '3ca3ea2f3d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('user', sa.String(length=200), nullable=False)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=200), nullable=False))
    op.drop_column('user', 'password_hash')
    op.alter_column('todo', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
